### ISSUE TITLE
Error on s3.js 

### ISSUE THREAD

**Issue by stubuchbinder** [googlecast/cast-custom-receiver#10]
I'm getting the following error when running 'node s3.js'

/Users/Stu/Sites/chromecast/s3.js:29
app.configure(function() {
    ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
    at Object.<anonymous> (/Users/Stu/Sites/chromecast/s3.js:29:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by trippedout** [comment]
i had this too - i think the latest express.js (or latest since this lib was published?) doesnt have configure anymore. http://expressjs.com/api.html 

i commented out `.configure(...)` and kept the `.use()` methods and it worked seemingly okay

then i just pushed the html file to my own server and that was way easier to deal with :)

**Comment by dhesson** [comment]
If you use npm install express@3.20.1 it will work fine (until the sample gets updated to work with latest version)
